deploy:android:
  stage: deploy
  before_script:
    - yarn
    - yarn link
  script:
    - cd android && ./gradlew assembleRelease
    - cp build/android/outputs/apk/release/app-release.apk $CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.apk
  artifacts:
    name: '$CI_PROJECT_NAME-$PLATFORM-$CI_COMMIT_REF_NAME'
    paths:
      - $CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.apk
    expire_in: 7 days
  when: manual
