export { AboutScreen } from './about';
export { HomeScreen } from './home';
export { NewsScreen, NewsDetailsScreen } from './news';
export { LibraryScreen, LibraryCardScreen } from './library';
export { default as TimeTableScreen } from './TimeTableScreen';
export { default as NotificationsScreen } from './NotificationsScreen';
export { default as SettingsScreen } from './SettingsScreen';
export { default as AccountScreen } from './SettingsScreen/AccountScreen';
export { default as MainConfigScreen } from './SettingsScreen/MainConfigScreen';
export { FinanceScreen } from './finances';
export { default as PersonalRatingScreen } from './PersonalRatingScreen';
export { default as QuestionnairesScreen } from './QuestionnairesScreen';
export { BuildingDormsScreen, ContactsScreen, DivisionsScreen } from './contacts';
export { ChatScreen } from './chats';
export { default as ParentsScreen } from './ParentsScreen';
export { default as ParentScreen } from './ParentsScreen/ParentScreen';
export { default as PersonalitiesScreen } from './PersonalitiesScreen';
export { default as PersonalityScreen } from './PersonalitiesScreen/PersonalityScreen';
