export { AboutScreen } from './about';
export { ChatScreen } from './chats';
export { BuildingDormsScreen, ContactsScreen, DivisionsScreen } from './contacts';
export { FinanceScreen } from './finances';
export { HomeScreen } from './home';
export { LibraryScreen, LibraryCardScreen } from './library';
export { NewsScreen, NewsDetailsScreen } from './news';
export { NotificationsScreen } from './notifications';
export { ParentScreen, ParentsListScreen } from './parents';
export { PersonalitiesScreen, PersonalityScreen } from './personalities';
export { PersonalRatingScreen } from './personal-rating';
export { QuestionnairesScreen } from './questionnaires';
export { AccountScreen, MainConfigScreen, SettingsScreen } from './settings';
export { TimeTableScreen } from './timetable';
export { WifiAccessScreen } from './wifiaccess';
export { ScratchBookScreen } from './scratchbook';
export { ReportsScreen } from './reports';
