export { default as HomeScreen } from './HomeScreen';
export { default as NewsScreen } from './NewsScreen';
export { default as NewsDetailsScreen } from './NewsScreen/NewsDetailsScreen';
export { default as LibraryScreen } from './LibraryScreen';
export { default as LibraryCardScreen} from './LibraryScreen/LibraryCardScreen';
export { default as TimeTableScreen } from './TimeTableScreen';
export { default as SettingsScreen } from './SettingsScreen';
export { default as AccountScreen } from './SettingsScreen/AccountScreen';
export { default as MainConfigScreen } from './SettingsScreen/MainConfigScreen';
export { default as FinanceScreen } from './FinanceScreen';
export { default as PersonalRatingScreen } from './PersonalRatingScreen';
export { default as QuestionnairesScreen } from './QuestionnairesScreen';
export { default as ContactsScreen } from './ContactsScreen';
export { default as DivisionsScreen } from './ContactsScreen/DivisionsScreen';
export { default as BuildingDormsScreen } from './ContactsScreen/BuildingDormsScreen';
