export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_PENDING = 'LOGOUT_PENDING';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const INIT_FIRST_STEP_RESET_PASSWORD = 'INIT_FIRST_STEP_RESET_PASSWORD';
export const SET_ERROR_RESET_PASSWORD = 'SET_ERROR_RESET_PASSWORD';

//library
export const LIBRARY_CARD_PENDING = 'LIBRARY_CARD_PENDING';
export const LIBRARY_CARD_SUCCESS = 'LIBRARY_CARD_SUCCESS';
export const LIBRARY_CARD_FAILURE = 'LIBRARY_CARD_FAILURE';
export const LIBRARY_BOOK_PENDING = 'LIBRARY_BOOK_PENDING';
export const LIBRARY_BOOK_SUCCESS = 'LIBRARY_BOOK_SUCCESS';
export const LIBRARY_BOOK_FAILURE = 'LIBRARY_BOOK_FAILURE';
export const LIBRARY_QRCODE_PENDING = 'LIBRARY_QRCODE_PENDING';
export const LIBRARY_QRCODE_SUCCESS = 'LIBRARY_QRCODE_SUCCESS';
export const LIBRARY_QRCODE_FAILURE = 'LIBRARY_QRCODE_FAILURE';

//news
export const NEWS_PENDING = 'NEWS_PENDING';
export const NEWS_SUCCESS = 'NEWS_SUCCESS';
export const NEWS_FAILURE = 'NEWS_FAILURE';
export const NEWS_PAGINATION_SUCCESS = 'NEWS_PAGINATION_SUCCESS';
export const NEWS_PAGINATION_FAILURE = 'NEWS_PAGINATION_FAILURE';
export const NEWS_PAGINATION = 'NEWS_PAGINATION';

export const UPDATE_PAGINATION_SUCCESS = 'UPDATE_PAGINATION_SUCCESS';
export const UPDATE_PAGINATION_FAILURE = 'UPDATE_PAGINATION_FAILURE';
export const UPDATE_PAGINATION = 'UPDATE_PAGINATION';
export const EVENTS_PAGINATION_SUCCESS = 'EVENTS_PAGINATION_SUCCESS';
export const EVENTS_PAGINATION_FAILURE = 'EVENTS_PAGINATION_FAILURE';
export const EVENTS_PAGINATION = 'EVENTS_PAGINATION';

//timeTableList
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_PENDING = 'SEARCH_PENDING';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

//finace
export const FINANCE_PAYMENT_PENDING = 'FINANCE_PAYMENT_PENDING';
export const FINANCE_PAYMENT_SUCCESS = 'FINANCE_PAYMENT_SUCCESS';
export const FINANCE_PAYMENT_FAILURE = 'FINANCE_PAYMENT_FAILURE';
export const FINANCE_SCHOLARSHIPS_PENDING = 'FINANCE_SCHOLARSHIPS_PENDING';
export const FINANCE_SCHOLARSHIPS_SUCCESS = 'FINANCE_SCHOLARSHIPS_SUCCESS';
export const FINANCE_SCHOLARSHIPS_FAILURE = 'FINANCE_SCHOLARSHIPS_FAILURE';

//contacts
export const DEPARTMENTS_SUCCESS = 'DEPARTMENTS_SUCCESS';
export const DEPARTMENTS_PENDING = 'DEPARTMENTS_PENDING';
export const DEPARTMENTS_FAILURE = 'DEPARTMENTS_FAILURE';

//Account
export const PHONE_EDIT_PENDING = 'PHONE_EDIT_PENDING';
export const PHONE_EDIT_SUCCESS = 'PHONE_EDIT_SUCCESS';
export const PHONE_EDIT_FAILURE = 'PHONE_EDIT_FAILURE';

//Load
export const LOAD_PROGRESS = 'LOAD_PROGRESS';
export const LOAD_SUCCESS = 'LOAD_SUCCESS';
export const LOAD_FAILURE = 'LOAD_FAILURE';

//Settings
export const SET_FONT_SIZE = 'SET_FONT_SIZE';