export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_PENDING = 'LOGOUT_PENDING';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';


//library
export const LIBRARY_CARD_PENDING = 'LIBRARY_CARD_PENDING';
export const LIBRARY_CARD_SUCCESS = 'LIBRARY_CARD_SUCCESS';
export const LIBRARY_CARD_FAILURE = 'LIBRARY_CARD_FAILURE';
export const LIBRARY_BOOK_PENDING = 'LIBRARY_BOOK_PENDING';
export const LIBRARY_BOOK_SUCCESS = 'LIBRARY_BOOK_SUCCESS';
export const LIBRARY_BOOK_FAILURE = 'LIBRARY_BOOK_FAILURE';
export const LIBRARY_QRCODE_PENDING = 'LIBRARY_QRCODE_PENDING';
export const LIBRARY_QRCODE_SUCCESS = 'LIBRARY_QRCODE_SUCCESS';
export const LIBRARY_QRCODE_FAILURE = 'LIBRARY_QRCODE_FAILURE';

//news
export const NEWS_PENDING = 'NEWS_PENDING';
export const NEWS_SUCCESS = 'NEWS_SUCCESS';
export const NEWS_FAILURE = 'NEWS_FAILURE';
